---
all:
  children:
    corp_dcs:
      hosts:
        dc01.corp.local:
          ansible_host: 10.10.0.10
          ansible_user: Administrator
          ansible_password: "P@ssw0rd!CTF"
          vm_ram: 3072
          vm_role: "domain_controller"
        dc01.eu.corp.local:
          ansible_host: 10.10.0.11
          ansible_user: Administrator
          ansible_password: "P@ssw0rd!CTF"
          vm_ram: 2048
          vm_role: "child_domain_controller"
    corp_servers:
      hosts:
        ca01.corp.local:
          ansible_host: 10.10.0.12
          ansible_user: Administrator
          ansible_password: "P@ssw0rd!CTF"
          vm_ram: 2048
          vm_role: "adcs_server"
        file01.corp.local:
          ansible_host: 10.10.0.13
          ansible_user: Administrator
          ansible_password: "P@ssw0rd!CTF"
          vm_ram: 1536
          vm_role: "file_server"
        sql01.corp.local:
          ansible_host: 10.10.0.14
          ansible_user: Administrator
          ansible_password: "P@ssw0rd!CTF"
          vm_ram: 2048
          vm_role: "sql_server"
    corp_workstation:
      hosts:
        ws01.corp.local:
          ansible_host: 10.10.0.100
          ansible_user: Administrator
          ansible_password: "P@ssw0rd!CTF"
          vm_ram: 3072
          vm_role: "workstation"
    finance_dcs:
      hosts:
        dc01.finance.local:
          ansible_host: 10.20.0.10
          ansible_user: Administrator
          ansible_password: "P@ssw0rd!CTF"
          vm_ram: 2048
          vm_role: "finance_domain_controller"
    root_dcs:
      hosts:
        dc01.root.corp:
          ansible_host: 10.30.0.10
          ansible_user: Administrator
          ansible_password: "P@ssw0rd!CTF"
          vm_ram: 2048
          vm_role: "root_domain_controller"
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_scheme: http
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
